services:
  postgres:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    image: swagger-petstore-db:local
    pull_policy: never

  petstore:
    build:
      context: .
      dockerfile: Dockerfile
    image: swagger-petstore:local
    pull_policy: never
