import { useState } from 'react';
import { useParams, useSearchParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { ArrowRight, Check, Minus, Plus } from 'lucide-react';
import { api, isLive } from './api';
import { useStore } from './store';
import { ActionLink, Button, Empty, Loading } from './ui';
import { MediaImage } from './MediaImage';
import { animalLabels, statusLabels, type Item } from './models';
import { money } from './domain';
import { lineIssue } from './commerce';

export function ItemCard({ item, preview = false }: { item: Item; preview?: boolean }) {
  const { add, lines, cartBusy } = useStore(), inCart = lines.find((line) => line.id === item.id)?.quantity ?? 0;
  const unavailable = !!lineIssue(item, 1), image = item.images[0], seedPet = image?.mediaId?.startsWith('40000000') && item.kind === 'pet';
  const visual = <MediaImage id={image?.mediaId} url={image?.url} alt={image?.alt || item.name} thumb className={seedPet ? `pet-photo ${item.visual}` : `catalog-photo ${item.kind}`} />;
  return <article className="product-card" data-testid={preview ? "catalog-item-preview" : "catalog-item-card"} data-item-id={preview ? undefined : item.id} data-item-kind={item.kind}>{preview ? <div className="product-image">{visual}</div> : <ActionLink testId="catalog-item-image-link" to={`/catalog/${item.id}`} className="product-image" aria-label={`Подробнее: ${item.name}`}>{visual}</ActionLink>}<div className="product-copy">{preview ? <span className="product-title" data-testid="catalog-item-name">{item.name || 'Название карточки'}</span> : <ActionLink testId="catalog-item-title-link" className="product-title" to={`/catalog/${item.id}`}><span data-testid="catalog-item-name">{item.name}</span></ActionLink>}<p>{item.subtitle || (item.kind === 'pet' ? 'Питомец' : item.brand)}</p></div><div className="product-bottom"><span>{money(item.price)}</span>{!preview && (inCart ? <ActionLink testId="catalog-item-view-cart" to="/cart" className="add-button has-item"><Check size={17} /><span>В корзине · {inCart}</span></ActionLink> : <Button testId="catalog-item-add" className="add-button" disabled={unavailable || cartBusy} onClick={() => { void add(item); }}><Plus size={17} /><span>{unavailable ? 'Нет в наличии' : 'В корзину'}</span></Button>)}</div></article>;
}
function MockHome() {
  const { items, itemsLoading, catalogError } = useStore(), [animal, setAnimal] = useState('all');
  return <><section className="store-hero" data-testid="home-hero"><div className="store-hero-copy"><p className="store-kicker">Любим. Заботимся. Понимаем.</p><h1>Всё для тех,<br />кого вы любите</h1><p>Хороший корм, уютный дом<br />и счастливые хвостики рядом.</p><ActionLink testId="hero-catalog" className="primary-button" to="/catalog">Перейти в каталог <ArrowRight size={19} /></ActionLink></div><div className="store-hero-image"><img src="/images/pets-hero.png" alt="Собака и кошка отдыхают рядом в солнечном доме" fetchPriority="high" /></div></section><section className="featured"><div className="section-heading"><h2>Популярное для питомцев</h2><ActionLink testId="all-products" className="text-link" to="/catalog">Все товары <ArrowRight size={18} /></ActionLink></div><div className="featured-tabs">{[['all', 'Всё'], ['dog', 'Для собак'], ['cat', 'Для кошек']].map(([id, name]) => <Button key={id} testId={`featured-${id}`} className={animal === id ? 'selected' : ''} aria-pressed={animal === id} onClick={() => setAnimal(id)}>{name}</Button>)}</div>{itemsLoading ? <Loading /> : catalogError ? <CatalogFailure /> : <div className="product-grid" data-testid="featured-items">{items.filter((item) => item.kind === 'product' && (animal === 'all' || item.animalTypes.some((value) => value === animal))).slice(0, 4).map((item) => <ItemCard key={item.id} item={item} />)}</div>}</section><section className="pet-invite"><div><p className="eyebrow">Новая история вместе</p><h2>Встретить своего друга</h2><p>У каждого питомца — свой характер.<br />Познакомьтесь, прежде чем выбирать.</p></div><ActionLink testId="home-pets" className="outline-button" to="/pets">Познакомиться <ArrowRight size={18} /></ActionLink></section></>;
}
function CatalogFailure() { const { refresh } = useStore(); return <Empty title="Не удалось загрузить каталог" text="Попробуйте ещё раз. Корзина сохранена."><Button testId="catalog-retry" className="outline-button" onClick={() => { void refresh(); }}>Повторить</Button></Empty>; }
function CatalogView({ pets = false }: { pets?: boolean }) {
  const { items, itemsLoading, catalogError } = useStore(), [params, setParams] = useSearchParams();
  const categories = useQuery({ queryKey: ['categories'], queryFn: api.categories });
  const value = (name: string) => params.get(name) ?? '';
  const change = (name: string, next: string) => { const copy = new URLSearchParams(params); if (next) copy.set(name, next); else copy.delete(name); setParams(copy, { replace: true }); };
  const visible = items.filter((item) => item.kind === (pets ? 'pet' : 'product') && (!value('q') || `${item.name} ${item.brand} ${item.sku} ${item.subtitle}`.toLowerCase().includes(value('q').toLowerCase())) && (!value('animal') || item.animalTypes.some((animal) => animal === value('animal'))) && (!value('type') || item.category === value('type')) && (!value('category') || item.categoryId === value('category')) && (!value('available') || !lineIssue(item, 1))).sort((a, b) => value('sort') === 'price-up' ? a.price - b.price : value('sort') === 'price-down' ? b.price - a.price : a.name.localeCompare(b.name, 'ru'));
  return <section className="catalog-page"><ActionLink testId="catalog-back" className="back-link" to="/">‹ На главную</ActionLink><div className="catalog-heading"><div><p className="eyebrow">Забота каждый день</p><h1>{pets ? 'Знакомьтесь, ваши друзья' : value('animal') === 'dog' ? 'Товары для собак' : value('animal') === 'cat' ? 'Товары для кошек' : 'Всё для вашего друга'}</h1></div><span>{visible.length} позиций</span></div><div className="catalog-controls"><div className="filter-tabs">{(pets ? [['', 'Все питомцы']] : [['', 'Всё'], ['food', 'Корм'], ['accessory', 'Для дома']]).map(([id, name]) => <Button key={id} testId={`filter-${id || 'all'}`} className={value('type') === id ? 'selected' : ''} aria-pressed={value('type') === id} onClick={() => change('type', id)}>{name}</Button>)}</div><div className="catalog-tools"><input data-testid="catalog-search" aria-label="Поиск в каталоге" type="search" placeholder="Найти своё" value={value('q')} onChange={(event) => change('q', event.target.value)} /><select data-testid="catalog-sort" aria-label="Сортировка" value={value('sort')} onChange={(event) => change('sort', event.target.value)}><option value="">По названию</option><option value="price-up">Сначала дешевле</option><option value="price-down">Сначала дороже</option></select></div></div><div className="catalog-filter-row"><select data-testid="catalog-animal" aria-label="Для какого животного" value={value('animal')} onChange={(event) => change('animal', event.target.value)}><option value="">Все животные</option>{Object.entries(animalLabels).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select><select data-testid="catalog-category" aria-label="Категория" value={value('category')} onChange={(event) => change('category', event.target.value)}><option value="">Все категории</option>{categories.data?.filter((category) => category.kind === (pets ? 'pet' : 'product')).map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><label className="checkbox-label"><input data-testid="catalog-available" type="checkbox" checked={!!value('available')} onChange={(event) => change('available', event.target.checked ? 'true' : '')} />В наличии</label>{params.size > 0 && <Button testId="reset-filters" className="text-link" onClick={() => setParams({})}>Сбросить</Button>}</div>{itemsLoading ? <Loading /> : catalogError ? <CatalogFailure /> : visible.length ? <div className="product-grid" data-testid="catalog-items">{visible.map((item) => <ItemCard key={item.id} item={item} />)}</div> : <Empty title="Пока ничего не нашли" text="Попробуйте другое название или категорию."><Button testId="empty-reset" className="outline-button" onClick={() => setParams({})}>Сбросить поиск</Button></Empty>}{pets && <p className="demo-note">Питомцы и изображения вымышлены и используются для демонстрации.</p>}</section>;
}
export function ItemDetail() {
  const { id } = useParams(), { items, itemsLoading, setLine, lines, cartBusy } = useStore(), [imageIndex, setImageIndex] = useState(0), [quantity, setQuantity] = useState(1);
  const item = items.find((entry) => entry.id === id);
  if (itemsLoading) return <Loading />;
  if (!item) return <Empty title="Карточка не найдена" text="Вернитесь в каталог и выберите другую позицию."><ActionLink testId="item-not-found-back" className="outline-button" to="/catalog">В каталог</ActionLink></Empty>;
  const image = item.images[imageIndex] ?? item.images[0], inCart = lines.some((line) => line.id === item.id), issue = lineIssue(item, quantity);
  return <section className="detail-page"><ActionLink testId="detail-back" className="back-link" to={item.kind === 'pet' ? '/pets' : '/catalog'}>‹ Назад в каталог</ActionLink><div className="full-detail-grid"><div><div className="full-detail-image" data-testid="product-image"><MediaImage id={image?.mediaId} url={image?.url} alt={image?.alt || item.name} className={item.kind === 'pet' && image?.mediaId?.startsWith('40000000') ? `pet-photo ${item.visual}` : `catalog-photo ${item.kind}`} /></div><div className="gallery-thumbs" data-testid="product-gallery">{item.images.map((entry, index) => <Button testId="product-gallery-thumbnail" data-media-id={entry.mediaId} data-image-index={index} key={entry.mediaId ?? entry.url} className={imageIndex === index ? 'selected' : ''} aria-label={`Фотография ${index + 1}`} aria-pressed={imageIndex === index} onClick={() => setImageIndex(index)}><MediaImage id={entry.mediaId} url={entry.url} alt={entry.alt || item.name} thumb /></Button>)}</div></div><div className="full-detail-copy"><p className="eyebrow">{item.kind === 'pet' ? 'Новый друг' : item.brand}</p><h1>{item.name}</h1><p className="muted">{item.subtitle}</p><p>{item.description}</p><dl className="attributes"><dt>Для кого</dt><dd>{item.animalTypes.map((animal) => animalLabels[animal]).join(', ')}</dd>{item.kind === 'product' ? <><dt>Артикул</dt><dd>{item.sku}</dd>{item.productType === 'FEED' && <><dt>Форма корма</dt><dd>{item.feedForm === 'DRY' ? 'Сухой' : 'Влажный'}</dd><dt>Вес</dt><dd>{item.netWeightGrams / 1000} кг</dd><dt>Возраст</dt><dd>{item.lifeStages.map((stage) => ({ YOUNG: 'Молодые', ADULT: 'Взрослые', SENIOR: 'Пожилые', ALL: 'Все возрасты' })[stage]).join(', ')}</dd></>}</> : <><dt>Статус</dt><dd>{statusLabels[item.status]}</dd>{item.birthDate && <><dt>Дата рождения</dt><dd>{item.birthDate}</dd></>}</>}</dl><div className="detail-buy"><strong>{money(item.price)}</strong><span>{issue ? 'Пока недоступен' : 'В наличии'}</span>{item.kind === 'product' && !inCart && <div className="quantity-controls"><Button testId="detail-quantity-minus" className="small-icon" disabled={quantity === 1} aria-label="Уменьшить количество" onClick={() => setQuantity(quantity - 1)}><Minus size={15} /></Button><span>{quantity}</span><Button testId="detail-quantity-plus" className="small-icon" disabled={quantity >= item.stock - item.reserved} aria-label="Увеличить количество" onClick={() => setQuantity(quantity + 1)}><Plus size={15} /></Button></div>}{inCart ? <ActionLink testId="detail-add" className="primary-button" to="/cart">Перейти в корзину</ActionLink> : <Button testId="detail-add" className="primary-button" disabled={!!issue || cartBusy} onClick={() => { void setLine(item.id, quantity); }}>В корзину <Plus size={18} /></Button>}</div>{item.ingredients && item.productType === 'FEED' && <div className="ingredients"><h3>Состав</h3><p>{item.ingredients}</p></div>}</div></div></section>;
}
export function About() { return <section className="about-page"><p className="eyebrow">Лапки — быть рядом</p><h1>Меньше лишнего.<br />Больше заботы.</h1><p>Питомцы, корм и вещи для ежедневной заботы — в одном магазине.</p><p>Это учебный магазин с демонстрационными данными и тестовой оплатой. {isLive ? 'Аккаунты, питомцы и заказы сохраняются на сервере.' : 'Созданные карточки, фотографии и заказы сохраняются в этом браузере.'}</p><ActionLink testId="about-catalog" className="primary-button" to="/catalog">Посмотреть товары <ArrowRight size={18} /></ActionLink></section>; }

export function Home() { return <MockHome />; }
export function Catalog(props: { pets?: boolean }) { return <CatalogView {...props} />; }
