FROM python:3.12-slim-bookworm@sha256:34386ef0cb081344d7ec1c103ba398e6e9f64e9ab3a1509accc92a4e24a07258
WORKDIR /workspace
COPY pyproject.toml requirements-runtime.txt ./
COPY src ./src
RUN python -m pip install --no-cache-dir --constraint requirements-runtime.txt -e '.[test,quality]'
COPY tests ./tests
COPY docker ./docker
COPY resources ./resources
COPY ui ./ui
COPY .github ./.github/
COPY docs/history.md ./docs/history.md
COPY Dockerfile docker-compose.yml .dockerignore .gitignore ./
ENTRYPOINT ["python", "-m", "pytest"]
