import { createRequire } from 'node:module';
import { strict as assert } from 'node:assert';
import { mkdir, writeFile } from 'node:fs/promises';
import { assertTestIdContract } from './assert-testid-contract.mjs';
const { chromium } = createRequire(import.meta.url)(process.env.LAPKI_PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.LAPKI_PREVIEW_URL || 'http://127.0.0.1:5173';
const browser = await chromium.launch({ channel: process.env.LAPKI_BROWSER_CHANNEL === 'bundled' ? undefined : process.env.LAPKI_BROWSER_CHANNEL || 'chrome', headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, locale: 'ru-RU', reducedMotion: 'reduce' });
const page = await context.newPage(); page.setDefaultTimeout(15000);
const errors = [], logs = [], results = []; let confirmationRequests = 0;
page.on('pageerror', (error) => errors.push(error.message));
page.on('console', (message) => { if (message.type() === 'info') logs.push(message.text()); });
page.on('request', (request) => { if (new URL(request.url()).pathname.startsWith('/api/v3/auth/confirm/')) confirmationRequests++; });
await mkdir('qa/screenshots', { recursive: true });
const pass = (name) => { results.push(name); console.log('PASS ' + name); };
async function goto(path) { await page.goto(base + path); await page.getByTestId('nav-home').waitFor(); }
async function api(path, method = 'GET', body) { return page.evaluate(async ({ path, method, body }) => { const response = await fetch('/api/v3' + path, { method, headers: body ? { 'Content-Type': 'application/json' } : {}, body: body ? JSON.stringify(body) : undefined }); return { status: response.status, data: await response.json() }; }, { path, method, body }); }
async function closeError(text) { await page.getByTestId('error-dialog').waitFor(); assert.match(await page.getByTestId('error-dialog').textContent(), text); await page.getByTestId('error-dismiss').click(); }
async function controls() { await assertTestIdContract(page); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false); }
function frontendLink(url) { const parsed = new URL(url); return '/confirm/' + parsed.pathname.split('/').at(-1) + parsed.search; }
try {
  await goto('/login?next=%2Fcheckout'); assert.equal(await page.getByTestId('auth-resend').count(), 0); assert.equal(await page.getByRole('link', { name: 'Подтвердить почту', exact: true }).count(), 0); await controls(); await page.screenshot({ path: 'qa/screenshots/login-unified.png' });
  await page.getByTestId('auth-register').click(); await page.getByTestId('registration-username').fill('flow_user'); await page.getByTestId('auth-name').fill('Тестовый'); await page.getByTestId('login-email').fill('flow@lapki.demo'); await page.getByTestId('login-password').fill('Flow123!');
  const response = page.waitForResponse((response) => response.url().endsWith('/auth/register') && response.request().method() === 'POST'); await page.getByTestId('login-submit').click(); const created = await response; assert.equal(created.status(), 201); const registration = await created.json(); const payload = created.request().postDataJSON(); assert.equal(payload.username, 'flow_user'); assert.equal(payload.firstName, 'Тестовый'); assert.equal('name' in payload, false);
  await page.waitForURL('**/register/verify'); await page.getByTestId('registration-email').waitFor(); assert.equal(await page.getByTestId('registration-email').textContent(), 'flow@lapki.demo'); assert.ok(Date.parse(registration.expiresAt) > Date.now() + 23 * 3600_000); assert.equal(await page.getByTestId('registration-resend-password').count(), 0); await controls(); await page.screenshot({ path: 'qa/screenshots/registration-verify.png' }); pass('signup moves directly to email step, backend fields, 24-hour link');
  const firstLink = await page.getByTestId('auth-demo-link').getAttribute('href'); await page.getByTestId('registration-resend').click(); await page.getByTestId('registration-sent-again').waitFor(); const secondLink = await page.getByTestId('auth-demo-link').getAttribute('href'); assert.notEqual(secondLink, firstLink);
  const old = new URL(firstLink, base); assert.equal((await api('/auth/confirm/' + old.pathname.split('/').at(-1) + old.search)).data.error, 'INVALID_CONFIRMATION_LINK'); pass('resend remains inside registration and invalidates previous link');
  await page.reload(); await page.getByTestId('registration-resend-password').waitFor(); assert.equal(await page.getByTestId('registration-email').textContent(), 'flow@lapki.demo'); assert.equal(await page.evaluate(() => JSON.stringify({ ...sessionStorage, ...localStorage }).includes('Flow123!')), false);
  await page.getByTestId('registration-resend-password').fill('Wrong123!'); await page.getByTestId('registration-resend').click(); await closeError(/Проверьте данные аккаунта/); assert.equal(await page.getByTestId('registration-resend-password').inputValue(), 'Wrong123!'); await page.getByTestId('registration-resend-password').fill('Flow123!'); await page.getByTestId('registration-resend').click(); await page.getByTestId('registration-sent-again').waitFor(); await page.waitForFunction((previous) => document.querySelector('[data-testid="auth-demo-link"]')?.getAttribute('href') !== previous, secondLink); pass('reload resumes email step without storing password; wrong credentials preserve input');
  const latest = await page.getByTestId('auth-demo-link').getAttribute('href'); await goto(firstLink); await page.getByTestId('registration-confirm-error').waitFor(); assert.match(await page.getByTestId('registration-confirm-error').textContent(), /Ссылка подтверждения не подходит/); await page.getByTestId('confirm-resend').click(); await page.getByTestId('registration-email').waitFor(); pass('invalid link explains the cause and returns to the same registration step');
  await goto(latest); await page.waitForURL('**/register/complete'); const beforeRepeat = confirmationRequests; await page.reload(); await page.getByTestId('registration-complete').waitFor(); assert.equal(confirmationRequests, beforeRepeat); await controls(); await page.screenshot({ path: 'qa/screenshots/registration-complete.png' });
  await page.getByTestId('confirm-login').click(); await page.getByTestId('login-email').waitFor(); assert.equal(await page.getByTestId('login-email').inputValue(), 'flow@lapki.demo'); assert.equal(new URL(page.url()).searchParams.get('next'), '/checkout'); assert.equal(await page.getByTestId('login-password').inputValue(), ''); pass('email click finishes registration, replay does not repeat confirmation, next and email preserved');
  const pending = await api('/auth/register', 'POST', { username: 'flow_pending', email: 'pending@lapki.demo', password: 'Short6', firstName: 'Новый' }); assert.equal(pending.status, 201); await goto('/login'); await page.getByTestId('login-email').fill('pending@lapki.demo'); await page.getByTestId('login-password').fill('Short6'); await page.getByTestId('login-submit').click(); await page.waitForURL('**/register/verify'); assert.equal(await page.getByTestId('error-dialog').count(), 0); assert.equal(await page.getByTestId('registration-email').textContent(), 'pending@lapki.demo'); await page.getByTestId('registration-resend').click(); await page.getByTestId('auth-demo-link').waitFor(); pass('ACCOUNT_NOT_VERIFIED resumes registration instead of separate menu or generic error');
  const expiryLink = await page.getByTestId('auth-demo-link').getAttribute('href'); await page.evaluate(async (userId) => { const db = await new Promise((resolve, reject) => { const request = indexedDB.open('lapki.mock.v3', 1); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); await new Promise((resolve, reject) => { const tx = db.transaction('state', 'readwrite'), store = tx.objectStore('state'), request = store.get('current'); request.onsuccess = () => { const state = request.result; state.confirmations.filter((link) => link.userId === userId && link.kind === 'confirm').forEach((link) => { link.expiresAt = Date.now() - 1000; }); store.put(state, 'current'); }; tx.oncomplete = resolve; tx.onerror = reject; }); db.close(); }, pending.data.user.id);
  await goto(expiryLink); await page.getByTestId('registration-confirm-error').waitFor(); assert.match(await page.getByTestId('registration-confirm-error').textContent(), /Срок действия ссылки истёк/); assert.equal(await page.getByTestId('registration-confirm-retry').count(), 0); await page.getByTestId('confirm-resend').click(); await page.getByTestId('registration-resend-password').fill('Short6'); await page.getByTestId('registration-resend').click(); await page.getByTestId('registration-sent-again').waitFor(); await page.getByTestId('auth-demo-link').click(); await page.waitForURL('**/register/complete'); pass('expired backend link offers new email and completes through the same flow');
  await goto('/register'); await page.getByTestId('registration-username').fill('flow_user'); await page.getByTestId('login-email').fill('other@lapki.demo'); await page.getByTestId('login-password').fill('Other123!'); await page.getByTestId('login-submit').click(); await closeError(/Аккаунт уже существует/); await page.getByTestId('registration-username-error').waitFor(); assert.equal(await page.getByTestId('registration-username').inputValue(), 'flow_user'); pass('USER_ALREADY_EXISTS identifies username conflict without losing registration data');
  for (let count = 0; count < 5; count++) { const result = await api('/auth/login', 'POST', { email: 'buyer@lapki.demo', password: 'Wrong123!' }); assert.equal(result.data.error, count === 4 ? 'LOGIN_RATE_LIMITED' : 'INVALID_CREDENTIALS'); }
  await goto('/login'); await page.getByTestId('login-email').fill('buyer@lapki.demo'); await page.getByTestId('login-password').fill('Buyer123!'); await page.getByTestId('login-submit').click(); await closeError(/Слишком много попыток/); pass('backend rate limit is simulated and presented in Russian');
  await page.evaluate(() => sessionStorage.removeItem('lapki.registration.v1')); await goto(latest); await page.waitForURL('**/register/complete'); await page.getByTestId('registration-complete').waitFor(); pass('ACCOUNT_ALREADY_CONFIRMED finishes the flow rather than displaying a technical error');
  for (const width of [360, 768, 1440]) { await page.setViewportSize({ width, height: 1000 }); await goto('/login'); await controls(); await goto('/register'); await controls(); await page.screenshot({ path: `qa/screenshots/registration-form-${width}.png`, fullPage: width === 1440 }); }
  assert.deepEqual(errors, []); for (const privateValue of ['Flow123!', 'Short6', 'Wrong123!', 'flow@lapki.demo', 'pending@lapki.demo']) assert.equal(logs.join('\n').includes(privateValue), false); pass('responsive flow, testids, no runtime errors and no credential leaks');
  await writeFile('qa/registration-result.json', JSON.stringify({ passed: true, baseUrl: base, results, runtimeErrors: errors }, null, 2)); console.log(JSON.stringify({ passed: true, cases: results.length }));
} catch (error) { await page.screenshot({ path: 'qa/screenshots/registration-failure.png', fullPage: true }); await writeFile('qa/registration-result.json', JSON.stringify({ passed: false, results, failure: String(error), runtimeErrors: errors, url: page.url() }, null, 2)); throw error; }
finally { await browser.close(); }
