import { createRequire } from 'node:module';
import { strict as assert } from 'node:assert';
import { mkdir } from 'node:fs/promises';
const { chromium } = createRequire(import.meta.url)(process.env.LAPKI_PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true, channel: process.env.LAPKI_BROWSER_CHANNEL === 'bundled' ? undefined : process.env.LAPKI_BROWSER_CHANNEL || 'chrome' });
await mkdir('qa/screenshots', { recursive: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const base = process.env.LAPKI_PREVIEW_URL || 'http://127.0.0.1:5173';
const errors = []; page.on('pageerror', (error) => errors.push(error.message));
await page.goto(base + '/');
await page.locator('.product-card').first().waitFor({ timeout: 20000 });
await page.waitForFunction(() => document.querySelectorAll('.product-card .product-image img').length === 4 && [...document.images].every((image) => image.complete && image.naturalWidth > 0));
await page.screenshot({ path: 'qa/screenshots/full-home.png', fullPage: true });
await page.goto(base + '/demo');
await page.getByTestId('demo-admin').click();
await page.getByRole('heading', { name: 'Магазин под контролем' }).waitFor();
await page.screenshot({ path: 'qa/screenshots/full-admin.png', fullPage: true });
await page.goto(base + '/admin/products/new');
await page.getByTestId('admin-item-name').waitFor();
await page.screenshot({ path: 'qa/screenshots/full-editor.png', fullPage: true });
assert.deepEqual(errors, []);
console.log(JSON.stringify({ errors, title: await page.title(), cards: await page.locator('.product-card').count() }));
await browser.close();
